site_name: My Docs

theme:
  name: material

markdown_extensions:
  - admonition # callouts
  - pymdownx.details # callouts
  - pymdownx.superfences # callouts, annotations
  - attr_list # annotations
  - md_in_html # annotations


