site_name: Ovenotes

theme:
  name: material
  palette:

    # Auto
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to auto mode

    # For light mode
    - media:  "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # For dark mode
    - media:  "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - content.code.annotate # global annotations
    - content.code.copy

markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition # callouts
  - pymdownx.details # callouts
  - pymdownx.superfences: # callouts, annotations
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list # annotations
  - abbr # abbreviations
  - md_in_html # annotations
  - pymdownx.highlight # highlighting
  - pymdownx.inlinehilite # inline highlighting
  - pymdownx.caret # for underlines
  - pymdownx.mark # for marking/highlighting
  - pymdownx.tilde # for strikethrough
  - pymdownx.keys # for showing keyboard keys



